# Generated by Django 5.2.4 on 2025-07-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.PositiveIntegerField(default=0, verbose_name='Зарезервировано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество'),
        ),
    ]
