# Generated by Django 5.2.4 on 2025-07-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_product_reserved_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reserved',
            new_name='reserved_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='total_quantity',
        ),
    ]
