# Generated by Django 5.2.4 on 2025-07-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
