# Generated by Django 5.2.4 on 2025-07-27 08:45

from django.db import migrations, models
import datetime
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_cart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='expires_at',
            field=models.DateTimeField(default=timezone.now() + datetime.timedelta(hours=2)),
        ),
    ]
