# Generated by Django 5.2.4 on 2025-07-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_cart_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
