# Generated by Django 5.2.4 on 2025-08-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_alter_cart_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('work_hours', models.TextField(verbose_name='Часы работы')),
                ('vk_link', models.URLField(blank=True, verbose_name='VK')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Telegram')),
                ('whatsapp_link', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('map_embed_code', models.TextField(help_text='HTML-код для вставки карты', verbose_name='Код карты')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
    ]
